### ISSUE TITLE
01.00.10 Emon mmrdust has no level information

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#180] opened 2017-05-15 16:52 UTC
Emon mmrdust has no level information.   If it is on model levels it duplicates AERmon mmrdust.

**Comment by StephanieWoodward** [comment] 2017-05-30 09:31
I have confirmation from PMIP lead that this can be deleted.  The diagnostic is wanted on all levels, so is a duplicate of the AERmon mmrdust request.

**Comment by martinjuckes** [comment] 2017-06-05 07:50
Fixed in 01.00.11

**Closed as completed by martinjuckes** 2017-06-05 07:50 UTC
