### ISSUE TITLE
od550aerso od550aerstrat od550so4so

### ISSUE THREAD

**Issue by oligan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#237] opened 2017-09-15 14:34 UTC
What differences between these three variables requested in atmos realm? 
the last one is sulphate only, the first two are all aerosols, that's ok... 
but what difference between the two first stratospheric AOD ?

**Comment by martinjuckes** [comment] 2017-09-27 10:28
od550aerstrat has been removed in 01.00.15 .. it was a duplicate of od550aerso.

od550aerso is all stratispheric aerosol, od550so4so is the sulphate aerosol in the stratosphere .. as you say.

**Closed as completed by martinjuckes** 2017-09-27 10:28 UTC
