### ISSUE TITLE
Misc. issues.

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#120] opened 2017-03-09 00:31 UTC
1.  the variable "orogis" in LImon seems to be the same physical quantity as "orog" in lmonAnt, ImonGre, IyrAnt, and lyrGre.  I think they should all be assigned the same name.  Also, is orogis in LImon needed?  It seems to duplicate (on a different grid) "orog" in lmonAnt and lmonGre.

2.  The variables in Efx have frequency = "fx", but dimensions include in most cases "time".  I think these should probably be time-independent or they should be moved to a more appropriate table.  If some are truly "fixed", then they may duplicate variables already in "fx" and should be removed.

3.  zg500 found in 6hrLev is defined on a pressure level and should be moved to 6hrPlev

4.  in 6hrLev, bs550aer and ec550aer should be defined as "time: point",  Otherwise it will be confusing to users who will have to write two *different* surface pressures (needed for converting from level to pressure) -- one that is a time mean and the other that is "point".  Should I contact AerChemMIP about this?

5.  With one or two exceptions, there should be no reason to get pmlev (6hrLev table) because it can be calculated from the model level information already collected.    We should note this in the request.  If we retain it, I think it should be scientifically sufficient to collect a climatological mean value.  Should I contact PMIP about this?     Also this variable is the same (I think) as pmlev found in 6hrLev.  The names should be the same.

6.  pfull and phalf are requested in various tables, but they are only needed from theta coordinate or height coordinate models (not sigma, or hybrid sigma, which almost everyone runs).  pressure can be calculated from the model level data and the "z factors" recorded in all files.  This should be made clear somewhere in the data request.

**Comment by martinjuckes** [comment] 2017-03-20 16:41
1. orogIs/LImon is the same as orog/ImonAnt etc, but on a different grid.
I've raised another ticket on this: https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/132 as there are a couple of associated issues.

2, 3,4: I can fix these.

5,6: I think pmlev is the same as phalf, and the issue is that it is only needed for a small sub-set of the CMIP6 models. I'll add a note to make this clear.

**Comment by martinjuckes** [comment] 2017-06-12 12:37
All fixed in 01.00.12

**Closed as completed by martinjuckes** 2017-06-12 12:37 UTC
